name: release-version
run-name: "Release ${{ github.event.ref }}"
on:
  push:
    tags:
      - "*"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build code
        run: cargo build --release

      - name: Save binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-linux
          path: target/release/margo

  release:
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine tag
        run: |
          tag=$(echo ${{github.event.ref}} | cut -d/ -f3)
          echo "tag=${tag}" >> $GITHUB_ENV

      - name: Download binary artifacts
        uses: actions/download-artifact@v4
        with:
          name: binary-linux
          path: linux

      - name: Fix artifact permissions
        run: chmod +x linux/margo

      - name: Compress artifacts
        run: tar czf margo-linux-x86_64.tar.gz -C linux margo

      - name: Release
        run: gh release create ${tag} margo-linux-x86_64.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
